# Generated by Django 6.0.6 on 2026-07-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('licencia_conducir', models.CharField(blank=True, max_length=30, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to='accounts.empleado')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['zona'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_CAMINO', 'En camino'), ('ENTREGADA', 'Entregada'), ('FALLIDA', 'Fallida'), ('REPROGRAMADA', 'Reprogramada')], default='ASIGNADA', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='orders.pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='delivery.repartidor')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
